id: P1639B1BF
initial_creation_type: input
source_metadata:
  title: Kunga Palden Series
  language: bo
  description: 'Texts by and about the renunciant Kunga Palden (kun dga'' dpal ldan,
    1878–1944):'
  volume:
    6828fc4ec84144189528f4ff91216e5b:
      title: 'Wondrous Light of Lunar Nectar: The Biography of Chatral Kunga Palden,
        a Yogin of the Supreme Vehicle'
      parent: Biographies
created_at: '2022-03-01T00:32:18.385348'
last_modified_at: '2022-03-01T00:32:18.385351'
